# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Batcave
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Bruce Wu
baseurl: ""
url: "https://brucewayne-batty.github.io/"
permalink: /:year/:month/:day/:title
repository: BruceWayne-Batty/BruceWayne-Batty.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/BruceWayne-Batty"
user: "Bruce Wu"
user_email: "zhongyuewu@link.cuhk.edu.cn"
contact_url: "https://goo.gl/tVljbV"
# Google Analytics 4 (GA4) Measurement ID (format: G-XXXXXXXXXX)
# Get your GA4 Measurement ID from: https://analytics.google.com/
# Note: This uses the new GA4 gtag.js, not the old Universal Analytics
google_tracking_id: "G-JVHV2KPG5C"  # Replace with your GA4 Measurement ID (G-XXXXXXXXXX)
# google_site_verification: "UA-96359860-1"  "no longer used"
disqus_shortname: "brucewayne-batty"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
  encoding: utf-8
future: true
encoding: utf-8